login:
    path: /{_locale}/login
    defaults: { _controller: UserBundle:User:login }
    requirements:
        _locale: "%app.locales%"

login_check:
    path: /{_locale}/login_check
    requirements:
        _locale: "%app.locales%"

logout:
    path: /{_locale}/logout
    requirements:
        _locale: "%app.locales%"
