<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerRepository extends EntityRepository
{
	public function findCurrentPlayer($experimentId, $userId)
	{
		// Find and return unassigned player
		$queryStr = "SELECT p FROM AppBundle:Player p WHERE p.experiment = :expId AND p.session IS NULL AND p.role IS NULL AND p.user = :userId";
		$query = $this->getEntityManager()->createQuery($queryStr);
		$query->setParameter('expId', $experimentId);
		$query->setParameter('userId', $userId);		
		$result = $query->getResult();
		
		if(count($result) > 0)
			return $result[0];
		
		// Find currently running sessions and return associated player
		$queryStr = "SELECT p FROM AppBundle:Player p JOIN AppBundle:Session s WHERE p.session = s.id AND p.user = :userId AND s.status < 2";
		$query = $this->getEntityManager()->createQuery($queryStr);
		$query->setParameter('userId', $userId);
		$result = $query->getResult();
		
		if(count($result) > 0)
			return $result[0];

		// No player found
		return null;
	}
}
