<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SessionRepository extends EntityRepository
{
	public function findAll($experiment = null)
	{
		if($experiment)
			return $this->findBy(array('experiment' => $experiment), array('started' => 'DESC'));
		else		
			return $this->findBy(array(), array('started' => 'DESC'));		
	}
}
